### ISSUE TITLE
CPU, RAM, Disk, Network and GPU tabs empty and not automatically refreshing

### ISSUE THREAD

**Issue by CrazyVito11** [hakandundar34coding/system-monitoring-center#151]
It seems like this broke a couple weeks ago, on both my desktop and laptop the tabs do not load, and the processes list and stats at the top of the application do not update anymore.

![image](https://user-images.githubusercontent.com/31567466/226958116-359748f9-c640-494c-9bc0-3eac6146fad1.png)

Both systems are fully up to date and running KDE. Laptop is running X11 _(AMD + Nvidia)_, desktop is on Wayland _(AMD)_.
I also saw [this issue](https://github.com/hakandundar34coding/system-monitoring-center/issues/148) that seems to describe the same issue. But updating to the latest version _(AUR 2.8.1 reports, application reports 2.8.0)_ didn't seem to help.

![image](https://user-images.githubusercontent.com/31567466/226960875-7fce2edb-9da8-4cab-a61a-bf7b18f04782.png)
I do find it weird that it reports **2.8.0** on both systems, while they are both up to date with the AUR that reports **2.8.1**, maybe that is a clue?

Please let me know if you need any more information!

**Terminal output:**
```
(python:5044): Adwaita-WARNING **: 16:36:20.354: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/MainWindow.py", line 411, in on_main_window_show
    self.main_gui_tab_switch()
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/MainWindow.py", line 689, in main_gui_tab_switch
    from .Cpu import Cpu
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Cpu.py", line 502, in <module>
    Cpu = Cpu()
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Cpu.py", line 20, in __init__
    self.tab_gui()
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Cpu.py", line 36, in tab_gui
    self.information_grid()
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Cpu.py", line 102, in information_grid
    scrolledwindow, self.average_usage_label, self.frequency_label = Common.styled_information_scrolledwindow(_tr("Average Usage"), _tr("Average CPU usage of all cores"), _tr("Frequency"), None)
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 693, in styled_information_scrolledwindow
    style_provider_scrolledwindow_separator()
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/Common.py", line 679, in style_provider_scrolledwindow_separator
    style_provider_scrolledwindow.load_from_data(css)
TypeError: Gtk.CssProvider.load_from_data() takes exactly 3 arguments (2 given)
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/systemmonitoringcenter/MainWindow.py", line 1157, in main_gui_tab_loop
    GLib.idle_add(Cpu.cpu_loop_func)
NameError: name 'Cpu' is not defined
```

**Neofetch laptop**
![image](https://user-images.githubusercontent.com/31567466/226957858-d00a3031-7a2b-460c-a86f-ef26dc816f9f.png)

**Neofetch desktop**
![image](https://user-images.githubusercontent.com/31567466/226959868-3e905cb9-f65a-4cd8-b9ed-22d353c07985.png)

**Comment by hakandundar34coding** [comment]
This error was printed after GTK 4.10 update. But it has been fixed on SMC v2.8.1.

It looks like the application is not updated on your system.  Can you check the installed version of the application by using your package manager?
Removing and installing the application again may fix the problem.

**Comment by CrazyVito11** [comment]
```
[sander@PC-SANDER ~]$ pacman -Q system-monitoring-center 
system-monitoring-center 2.8.1-1
[sander@PC-SANDER ~]$ 
```

After this I removed the package and recompiled it, that didn't fix it.
But after I completely removed the folder, cloned it again and then compiled it, it started working again.

Weird, but it's resolved now. Thanks!
