### ISSUE TITLE
Disk Usage Of Parent Disk And Disk Model For NVMe SSDs Are Not Shown

### ISSUE THREAD

**Issue by govarthenan** [hakandundar34coding/system-monitoring-center#2]
Disk tab automatically selects the home partition, which results, at least with my SSD, in no metrics displayed. Metrics are displayed correctly upon selecting the DDS device e.g nvme0n1 instead of nvme0n1p6, which was selected by default. - [Screenshot](https://ibb.co/tqXrf5C) and debug message:
```
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/src/Disk.py", line 271, in disk_loop_func
    disk_get_device_partition_model_name_mount_point_func()
  File "/usr/share/system-monitoring-center/src/Disk.py", line 385, in disk_get_device_partition_model_name_mount_point_func
    with open("/sys/class/block/" + parent_disk + "/device/model") as reader:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/block/nvme0n1p/device/model'
```

Additional information:
```
[gova@fedora ~]$ ls /sys/class/block/
total 0
drwxr-xr-x.  2 root root 0 Dec  2 14:30 ./
drwxr-xr-x. 76 root root 0 Dec  2 13:47 ../
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1p1 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p1/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1p2 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p2/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1p3 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p3/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1p4 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p4/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1p5 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p5/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1p6 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p6/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1p7 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p7/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 zram0 -> ../../devices/virtual/block/zram0/
```

```
[gova@fedora ~]$ cat /proc/mounts 
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
sysfs /sys sysfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,seclabel,nosuid,size=7859896k,nr_inodes=1964974,mode=755,inode64 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,seclabel,nosuid,nodev,inode64 0 0
devpts /dev/pts devpts rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,seclabel,nosuid,nodev,size=3168180k,nr_inodes=819200,mode=755,inode64 0 0
cgroup2 /sys/fs/cgroup cgroup2 rw,seclabel,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
none /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
/dev/nvme0n1p6 / btrfs rw,seclabel,relatime,compress=zstd:1,ssd,space_cache,subvolid=257,subvol=/root 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,nosuid,noexec,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=31,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=28223 0 0
mqueue /dev/mqueue mqueue rw,seclabel,nosuid,nodev,noexec,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
tracefs /sys/kernel/tracing tracefs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,seclabel,relatime,pagesize=2M 0 0
fusectl /sys/fs/fuse/connections fusectl rw,nosuid,nodev,noexec,relatime 0 0
configfs /sys/kernel/config configfs rw,nosuid,nodev,noexec,relatime 0 0
/dev/nvme0n1p6 /home btrfs rw,seclabel,relatime,compress=zstd:1,ssd,space_cache,subvolid=256,subvol=/home 0 0
tmpfs /tmp tmpfs rw,seclabel,nosuid,nodev,size=7920444k,nr_inodes=409600,inode64 0 0
/dev/nvme0n1p4 /mnt/BA9E0A209E09D633 fuseblk rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,blksize=4096 0 0
/dev/nvme0n1p5 /boot ext4 rw,seclabel,relatime 0 0
/dev/nvme0n1p3 /mnt/12DAA115DAA0F65F fuseblk rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,blksize=4096 0 0
/dev/nvme0n1p7 /mnt/01D7E10FC8B40900 fuseblk rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,blksize=4096 0 0
/dev/nvme0n1p1 /boot/efi vfat rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=winnt,errors=remount-ro 0 0
sunrpc /var/lib/nfs/rpc_pipefs rpc_pipefs rw,relatime 0 0
tmpfs /run/user/1000 tmpfs rw,seclabel,nosuid,nodev,relatime,size=1584088k,nr_inodes=396022,mode=700,uid=1000,gid=1000,inode64 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
portal /run/user/1000/doc fuse.portal rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
portal /root/.cache/doc fuse.portal rw,nosuid,nodev,relatime,user_id=0,group_id=0 0 0
gvfsd-fuse /root/.cache/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=0,group_id=0 0 0
```

**Comment by hakandundar34coding** [comment]
You have a machine with new hardware. I will make some changes on the code for fixing the problems.
Can you write output of these commands?
```
Open '/sys/class/block/nvme0n1p/device' directory from file browser and open terminal here. Type these commands:
ls
cd ..
ls
cd ..
ls
cd ..
ls
```

I am looking for ```model``` file for reading the disk device model. This file is in ```device``` folder in the parent disk folder.

**Comment by govarthenan** [comment]
As far as i know, the device's name is `nvme0n1`, not `nvme0n1p`, and there is no folder with the path of `/sys/class/block/nvme0n1p`. Folder like `/sys/class/block/nvme0n1p4`, `/sys/class/block/nvme0n1p6` exist, which lead to the partitions I've mounted. And my laptop contains only one SSD. It's manufactured by SK Hynix.

I think the trailing `p` hints at the partition number which would be next. So, I'm replacing the `nvme0n1p` in the commands you mentioned to `nvme0n1`. Correct me if I'm wrong.

```
[gova@fedora ~]$ ls /sys/class/block/nvme0n1
lrwxrwxrwx. 1 root root 0 Dec  2 14:30 /sys/class/block/nvme0n1 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/

[gova@fedora ~]$ ls -H /sys/class/block/nvme0n1
total 0
drwxr-xr-x. 16 root root    0 Dec  2 13:47 ./
drwxr-xr-x.  6 root root    0 Dec  2 13:47 ../
-r--r--r--.  1 root root 4.0K Dec  2 11:09 alignment_offset
lrwxrwxrwx.  1 root root    0 Dec  2 11:09 bdi -> ../../../../../../virtual/bdi/259:0/
-r--r--r--.  1 root root 4.0K Dec  2 08:17 capability
-r--r--r--.  1 root root 4.0K Dec  2 18:28 dev
lrwxrwxrwx.  1 root root    0 Dec  2 08:23 device -> ../../nvme0/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 discard_alignment
-r--r--r--.  1 root root 4.0K Dec  2 11:09 diskseq
-r--r--r--.  1 root root 4.0K Dec  2 11:09 eui
-r--r--r--.  1 root root 4.0K Dec  2 11:09 events
-r--r--r--.  1 root root 4.0K Dec  2 11:09 events_async
-rw-r--r--.  1 root root 4.0K Dec  2 11:09 events_poll_msecs
-r--r--r--.  1 root root 4.0K Dec  2 11:09 ext_range
-r--r--r--.  1 root root 4.0K Dec  2 11:09 hidden
drwxr-xr-x.  2 root root    0 Dec  2 08:17 holders/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 inflight
drwxr-xr-x.  2 root root    0 Dec  2 08:17 integrity/
drwxr-xr-x. 18 root root    0 Dec  2 08:17 mq/
-r--r--r--.  1 root root 4.0K Dec  2 22:57 nsid
drwxr-xr-x.  5 root root    0 Dec  2 13:47 nvme0n1p1/
drwxr-xr-x.  5 root root    0 Dec  2 13:47 nvme0n1p2/
drwxr-xr-x.  5 root root    0 Dec  2 13:47 nvme0n1p3/
drwxr-xr-x.  5 root root    0 Dec  2 13:47 nvme0n1p4/
drwxr-xr-x.  5 root root    0 Dec  2 13:47 nvme0n1p5/
drwxr-xr-x.  5 root root    0 Dec  2 13:47 nvme0n1p6/
drwxr-xr-x.  5 root root    0 Dec  2 13:47 nvme0n1p7/
drwxr-xr-x.  2 root root    0 Dec  2 08:17 power/
drwxr-xr-x.  2 root root    0 Dec  2 13:47 queue/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 range
-r--r--r--.  1 root root 4.0K Dec  2 08:17 removable
-r--r--r--.  1 root root 4.0K Dec  2 08:17 ro
-r--r--r--.  1 root root 4.0K Dec  2 08:17 size
drwxr-xr-x.  2 root root    0 Dec  2 13:47 slaves/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 stat
lrwxrwxrwx.  1 root root    0 Dec  2 14:30 subsystem -> ../../../../../../../class/block/
drwxr-xr-x.  2 root root    0 Dec  2 08:17 trace/
-rw-r--r--.  1 root root 4.0K Dec  2 14:30 uevent
-r--r--r--.  1 root root 4.0K Dec  2 22:57 wwid
```

The SSD's device folder.
```
[gova@fedora ~]$ ls /sys/class/block/nvme0n1/device/
total 0
drwxr-xr-x.  6 root root    0 Dec  2 13:47 ./
drwxr-xr-x.  3 root root    0 Dec  2 13:47 ../
-r--r--r--.  1 root root 4.0K Dec  2 11:09 address
-r--r--r--.  1 root root 4.0K Dec  2 11:09 cntlid
-r--r--r--.  1 root root 4.0K Dec  2 11:09 dev
lrwxrwxrwx.  1 root root    0 Dec  2 08:23 device -> ../../../0000:04:00.0/
-r--r--r--.  1 root root 4.0K Dec  2 22:58 firmware_rev
drwxr-xr-x.  3 root root    0 Dec  2 14:30 hwmon3/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 kato
-r--r--r--.  1 root root 4.0K Dec  2 19:32 model
drwxr-xr-x.  3 root root    0 Dec  2 14:30 ng0n1/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 numa_node
drwxr-xr-x. 16 root root    0 Dec  2 13:47 nvme0n1/
drwxr-xr-x.  2 root root    0 Dec  2 11:09 power/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 queue_count
--w-------.  1 root root 4.0K Dec  2 11:09 rescan_controller
--w-------.  1 root root 4.0K Dec  2 11:09 reset_controller
-r--r--r--.  1 root root 4.0K Dec  2 22:58 serial
-r--r--r--.  1 root root 4.0K Dec  2 11:09 sqsize
-r--r--r--.  1 root root 4.0K Dec  2 11:09 state
-r--r--r--.  1 root root 4.0K Dec  2 11:09 subsysnqn
lrwxrwxrwx.  1 root root    0 Dec  2 12:26 subsystem -> ../../../../../../class/nvme/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 transport
-rw-r--r--.  1 root root 4.0K Dec  2 12:26 uevent
```
SSD's model file:
```
[gova@fedora ~]$ cat /sys/class/block/nvme0n1/device/model 
HFM001TD3JX013N 
```

**Comment by hakandundar34coding** [comment]
I have found the problem. I will update the application tomorrow.

**Comment by govarthenan** [comment]
OK, I'm attaching the results you requested in the edited message as well. Please don't edit the comments as I can't give consistent information that way. 

```
[gova@fedora device]$ cd  /sys/class/block/nvme0n1/device
[gova@fedora device]$ ls
total 0
drwxr-xr-x.  6 root root    0 Dec  2 13:47 ./
drwxr-xr-x.  3 root root    0 Dec  2 13:47 ../
-r--r--r--.  1 root root 4.0K Dec  2 11:09 address
-r--r--r--.  1 root root 4.0K Dec  2 11:09 cntlid
-r--r--r--.  1 root root 4.0K Dec  2 11:09 dev
lrwxrwxrwx.  1 root root    0 Dec  2 08:23 device -> ../../../0000:04:00.0/
-r--r--r--.  1 root root 4.0K Dec  2 22:58 firmware_rev
drwxr-xr-x.  3 root root    0 Dec  2 14:30 hwmon3/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 kato
-r--r--r--.  1 root root 4.0K Dec  2 19:32 model
drwxr-xr-x.  3 root root    0 Dec  2 14:30 ng0n1/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 numa_node
drwxr-xr-x. 16 root root    0 Dec  2 13:47 nvme0n1/
drwxr-xr-x.  2 root root    0 Dec  2 11:09 power/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 queue_count
--w-------.  1 root root 4.0K Dec  2 11:09 rescan_controller
--w-------.  1 root root 4.0K Dec  2 11:09 reset_controller
-r--r--r--.  1 root root 4.0K Dec  2 22:58 serial
-r--r--r--.  1 root root 4.0K Dec  2 11:09 sqsize
-r--r--r--.  1 root root 4.0K Dec  2 11:09 state
-r--r--r--.  1 root root 4.0K Dec  2 11:09 subsysnqn
lrwxrwxrwx.  1 root root    0 Dec  2 12:26 subsystem -> ../../../../../../class/nvme/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 transport
-rw-r--r--.  1 root root 4.0K Dec  2 12:26 uevent
[gova@fedora device]$ cd ..
[gova@fedora nvme0n1]$ ls
total 0
drwxr-xr-x. 16 root root    0 Dec  2 13:47 ./
drwxr-xr-x.  6 root root    0 Dec  2 13:47 ../
-r--r--r--.  1 root root 4.0K Dec  2 11:09 alignment_offset
lrwxrwxrwx.  1 root root    0 Dec  2 11:09 bdi -> ../../../../../../virtual/bdi/259:0/
-r--r--r--.  1 root root 4.0K Dec  2 08:17 capability
-r--r--r--.  1 root root 4.0K Dec  2 18:28 dev
lrwxrwxrwx.  1 root root    0 Dec  2 08:23 device -> ../../nvme0/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 discard_alignment
-r--r--r--.  1 root root 4.0K Dec  2 11:09 diskseq
-r--r--r--.  1 root root 4.0K Dec  2 11:09 eui
-r--r--r--.  1 root root 4.0K Dec  2 11:09 events
-r--r--r--.  1 root root 4.0K Dec  2 11:09 events_async
-rw-r--r--.  1 root root 4.0K Dec  2 11:09 events_poll_msecs
-r--r--r--.  1 root root 4.0K Dec  2 11:09 ext_range
-r--r--r--.  1 root root 4.0K Dec  2 11:09 hidden
drwxr-xr-x.  2 root root    0 Dec  2 08:17 holders/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 inflight
drwxr-xr-x.  2 root root    0 Dec  2 08:17 integrity/
drwxr-xr-x. 18 root root    0 Dec  2 08:17 mq/
-r--r--r--.  1 root root 4.0K Dec  2 22:57 nsid
drwxr-xr-x.  5 root root    0 Dec  2 13:47 nvme0n1p1/
drwxr-xr-x.  5 root root    0 Dec  2 13:47 nvme0n1p2/
drwxr-xr-x.  5 root root    0 Dec  2 13:47 nvme0n1p3/
drwxr-xr-x.  5 root root    0 Dec  2 13:47 nvme0n1p4/
drwxr-xr-x.  5 root root    0 Dec  2 13:47 nvme0n1p5/
drwxr-xr-x.  5 root root    0 Dec  2 13:47 nvme0n1p6/
drwxr-xr-x.  5 root root    0 Dec  2 13:47 nvme0n1p7/
drwxr-xr-x.  2 root root    0 Dec  2 08:17 power/
drwxr-xr-x.  2 root root    0 Dec  2 13:47 queue/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 range
-r--r--r--.  1 root root 4.0K Dec  2 08:17 removable
-r--r--r--.  1 root root 4.0K Dec  2 08:17 ro
-r--r--r--.  1 root root 4.0K Dec  2 08:17 size
drwxr-xr-x.  2 root root    0 Dec  2 13:47 slaves/
-r--r--r--.  1 root root 4.0K Dec  2 11:09 stat
lrwxrwxrwx.  1 root root    0 Dec  2 14:30 subsystem -> ../../../../../../../class/block/
drwxr-xr-x.  2 root root    0 Dec  2 08:17 trace/
-rw-r--r--.  1 root root 4.0K Dec  2 14:30 uevent
-r--r--r--.  1 root root 4.0K Dec  2 22:57 wwid
[gova@fedora nvme0n1]$ cd ..
[gova@fedora block]$ ls
total 0
drwxr-xr-x.  2 root root 0 Dec  2 14:30 ./
drwxr-xr-x. 76 root root 0 Dec  2 13:47 ../
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1p1 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p1/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1p2 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p2/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1p3 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p3/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1p4 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p4/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1p5 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p5/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1p6 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p6/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 nvme0n1p7 -> ../../devices/pci0000:00/0000:00:02.4/0000:04:00.0/nvme/nvme0/nvme0n1/nvme0n1p7/
lrwxrwxrwx.  1 root root 0 Dec  2 14:30 zram0 -> ../../devices/virtual/block/zram0/
[gova@fedora block]$ cd ..
[gova@fedora class]$ ls
total 0
drwxr-xr-x. 76 root root 0 Dec  2 13:47 ./
dr-xr-xr-x. 13 root root 0 Dec  2 08:17 ../
drwxr-xr-x.  2 root root 0 Dec  2 13:47 ata_device/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 ata_link/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 ata_port/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 backlight/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 bdi/
drwxr-xr-x.  2 root root 0 Dec  2 14:30 block/
drwxr-xr-x.  2 root root 0 Dec  2 08:17 bluetooth/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 bsg/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 cpuid/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 devcoredump/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 devlink/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 dma/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 dma_heap/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 dmi/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 drm/
drwxr-xr-x.  2 root root 0 Dec  2 14:30 drm_dp_aux_dev/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 extcon/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 firmware/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 graphics/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 hidraw/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 hwmon/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 i2c-adapter/
drwxr-xr-x.  2 root root 0 Dec  2 08:17 ieee80211/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 input/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 intel_scu_ipc/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 iommu/
drwxr-xr-x.  2 root root 0 Dec  2 14:30 ipmi/
drwxr-xr-x.  2 root root 0 Dec  2 14:30 kfd/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 leds/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 lirc/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 mdio_bus/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 mem/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 misc/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 msr/
drwxr-xr-x.  2 root root 0 Dec  2 22:48 net/
drwxr-xr-x.  2 root root 0 Dec  2 14:30 nvme/
drwxr-xr-x.  2 root root 0 Dec  2 14:30 nvme-generic/
drwxr-xr-x.  2 root root 0 Dec  2 14:30 nvme-subsystem/
drwxr-xr-x.  2 root root 0 Dec  2 14:30 pci_bus/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 pcmcia_socket/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 phy/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 powercap/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 power_supply/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 pps/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 ptp/
drwxr-xr-x.  2 root root 0 Dec  2 14:30 pwm/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 rc/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 regulator/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 remoteproc/
drwxr-xr-x.  2 root root 0 Dec  2 12:26 rfkill/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 rtc/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 scsi_device/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 scsi_disk/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 scsi_generic/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 scsi_host/
drwxr-xr-x.  2 root root 0 Dec  2 08:17 sound/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 spi_master/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 thermal/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 tpm/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 tpmrm/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 tty/
drwxr-xr-x.  2 root root 0 Dec  2 14:30 typec/
drwxr-xr-x.  2 root root 0 Dec  2 14:30 typec_mux/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 usbmisc/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 usbmon/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 usb_role/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 vc/
drwxr-xr-x.  2 root root 0 Dec  2 13:36 video4linux/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 vtconsole/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 wakeup/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 watchdog/
drwxr-xr-x.  2 root root 0 Dec  2 14:30 wmi_bus/
drwxr-xr-x.  2 root root 0 Dec  2 13:47 wwan/
drwxr-xr-x.  2 root root 0 Dec  2 14:30 zram-control/
```

And where do I find that `rpm_packaging.sh` script?

**Comment by hakandundar34coding** [comment]
For v0.1.21-beta18, `rpm_packaging.sh` is in the main directory of the project. You can download this version from [tags](https://github.com/hakandundar34coding/system-monitoring-center/tags) or [releases](https://github.com/hakandundar34coding/system-monitoring-center/releases) links.

But for versions later than that it will be in `packaging_scripts/rpm_packaging.sh` directory.

I will update the application tomorrow and it will be in `packaging_scripts/rpm_packaging.sh` directory. Also 'disk stats' problem will be fixed.

Packages other than .deb wil be available for newer versions (RPM and pacman packages).

**Comment by govarthenan** [comment]
OK. GIve me a nudge after you update the app and I'll see if the problem has been fixed. Thanks.

**Comment by hakandundar34coding** [comment]
The code has been updated to fix this problem.

**Comment by govarthenan** [comment]
Commit 47d2c0ce8cd51ea1f71636090b5f98583fe8896a seems to have solved a few problems. 

The Disk tab is showing metrics properly by default upon opening it. However, I observed that still, **the default partition selected is the home partition**. Also, the app is showing disk activity which happens only on the selected partition. When I tried copy pasting files within another partition, those metrics weren't shown in the app, which had the home partition selected. I don't know whether this is desired behavior. 

Also, when I selected the SSD device, instead of a single partition, the disk space usage is shown [NOT DISPLAYED](https://ibb.co/ZWtWjTm).

**Comment by hakandundar34coding** [comment]
By default, System Monitoring Center selects system disk on Disk tab. But you can change this behavior from:
```Main Menu > Settings > Remember last selected hardware```
This is not a bug.

System Monitoring Center can also measure disk read/write speed, total read/write time of parent devices (SSD/HDD, USB devices, Virtual Devices, etc). You can select parent disk (SSD) and can view disk write/write speed when you copy a file from one partition to another one.
Can you share a video if you think there is a bug for showing disk speed of paren disk (SSD device)?

HDD/SSD device (parent of partitions) does not have a filesystem and disk usage of them can not be calculated. This is not a bug. You can view disk usage of the partitions by selecting them. The application wil show this information if selected disk is a partition.

But your disk model name is not displayed. There is a bug. Can you share output of this command?
cat /sys/class/block/nvme0n1/device/vendor

**Comment by govarthenan** [comment]
The specified directory doesn't have the `vendor` file. 
```
[gova@fedora ~]$ ls /sys/class/block/nvme0n1/device/
total 0
drwxr-xr-x.  6 root root    0 Dec  4 09:20 ./
drwxr-xr-x.  3 root root    0 Dec  4 09:20 ../
-r--r--r--.  1 root root 4.0K Dec  4 19:34 address
-r--r--r--.  1 root root 4.0K Dec  4 19:34 cntlid
-r--r--r--.  1 root root 4.0K Dec  4 19:34 dev
lrwxrwxrwx.  1 root root    0 Dec  4 19:34 device -> ../../../0000:04:00.0/
-r--r--r--.  1 root root 4.0K Dec  4 19:34 firmware_rev
drwxr-xr-x.  3 root root    0 Dec  4 16:39 hwmon3/
-r--r--r--.  1 root root 4.0K Dec  4 19:34 kato
-r--r--r--.  1 root root 4.0K Dec  4 19:34 model
drwxr-xr-x.  3 root root    0 Dec  4 19:34 ng0n1/
-r--r--r--.  1 root root 4.0K Dec  4 19:34 numa_node
drwxr-xr-x. 16 root root    0 Dec  4 09:20 nvme0n1/
drwxr-xr-x.  2 root root    0 Dec  4 19:34 power/
-r--r--r--.  1 root root 4.0K Dec  4 19:34 queue_count
--w-------.  1 root root 4.0K Dec  4 19:34 rescan_controller
--w-------.  1 root root 4.0K Dec  4 19:34 reset_controller
-r--r--r--.  1 root root 4.0K Dec  4 19:34 serial
-r--r--r--.  1 root root 4.0K Dec  4 19:34 sqsize
-r--r--r--.  1 root root 4.0K Dec  4 19:34 state
-r--r--r--.  1 root root 4.0K Dec  4 19:34 subsysnqn
lrwxrwxrwx.  1 root root    0 Dec  4 17:11 subsystem -> ../../../../../../class/nvme/
-r--r--r--.  1 root root 4.0K Dec  4 19:34 transport
-rw-r--r--.  1 root root 4.0K Dec  4 17:11 uevent
```

However, the  symlink `devcice` inside the folder leads to `/sys/class/block/nvme0n1/device/device` has the file `'vendor`.
```
[gova@fedora ~]$ cat /sys/class/block/nvme0n1/device/device/vendor
0x1c5c
```

**Comment by hakandundar34coding** [comment]
Currently, the code can read only vendor file (not symlink). I will fix this problem.

**Comment by hakandundar34coding** [comment]
The code has been updated to fix the disk vendor name problem.

You can download Disk.py file (from: https://github.com/hakandundar34coding/system-monitoring-center/blob/master/src/Disk.py) and replace it manually (directory: ```/usr/share/system-monitoring-center/src/```).

Can you write if the problem is fixed?

**Comment by govarthenan** [comment]
I tried to build the latest commit and I'm getting the following error:

```
[gova@fedora system-monitoring-center]$ ./packaging_scripts/rpm_packaging.sh
error: failed to stat /home/gova/gitclone/system-monitoring-center.spec: No such file or directory
```
I tried running as sudo and got the same result. 
I reverted to fe07633 and tried building, which succeeded. [But there is no SSD name to be seen.](https://ibb.co/sqBBqvs)

**Comment by hakandundar34coding** [comment]
I have updated the code.
Can you try new Disk.py file? (You can download only Disk.py file and replace it instead of downlaoding the whole project). I will update the application and packages in 1-2 days.

**Comment by govarthenan** [comment]
I still keep getting that error:
```
[gova@192 system-monitoring-center]$ ./packaging_scripts/rpm_packaging.sh 
error: failed to stat /home/gova/gitclone/system-monitoring-center.spec: No such file or directory
```
I downloaded `Disk.py` and replaced it in `/usr/share/system-monitoring-center/src/` and the [name is still not displayed](https://ibb.co/ZdqNtBy) in the Disk tab.

**Comment by hakandundar34coding** [comment]
Disk device vendor-model information bug is fixed in the last update.

About ```rpm_packaging.sh``` script:
This file have to be run in a folder that one level under the main directory of the project. It works if you run it by opening terminal in the folder that contains this script file. By default, this script file is in ```/packaging_scripts``` folder. You do not have to change its location. Open a terminal in ```/packaging_scripts/``` and run the script file.

RPM packages are uploaded for new versions of the application. You can download and install them easily.
